In [38]:
import os
import pandas as pd
import numpy as np
import cv2
import supervision as sv
import matplotlib.pyplot as plt
import shutil
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
HOLE_DATASET_LOC = r"D:\CountAI_Projects\Datasets\archive\captured\Hole"
HOLE_ANNOTATIONS_LOC = r"D:\CountAI_Projects\Datasets\archive\hole"

In [3]:
DF = pd.DataFrame(columns = ["Image_Name","Image_Width","Image_Height","Image_Location"])

In [4]:
def read_the_dataset(dataset_loc):

    for file in os.listdir(dataset_loc):

        image_name = file.split(".")[0]
        
        image_loc = os.path.join(dataset_loc,file)
        img = cv2.imread(image_loc)

        h,w,_ = img.shape

        DF.loc[len(DF)] = {"Image_Name":image_name,"Image_Location":image_loc,"Image_Width":w,"Image_Height":h}

In [5]:
read_the_dataset(HOLE_DATASET_LOC)

In [6]:
DF

,Image_Name,Image_Width,Image_Height,Image_Location
0,20180531_134722,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
1,20180531_134730,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
2,20180531_135018,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
3,20180531_135032,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
4,20180531_135038,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
5,20180531_135110,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
6,20180531_135111,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
7,20180531_135129,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
8,20180531_135705,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
9,20180531_135709,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
10,20180531_135742,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
11,20180531_135806,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
12,20180531_141608,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
13,20180531_141626,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
14,20180531_141640,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
15,hole_2018-10-11 12_59_30,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
16,hole_2018-10-11 13_00_10,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
17,hole_2018-10-11 13_00_42,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
18,hole_2018-10-11 13_02_35,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
19,hole_2018-10-11 13_04_48,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
20,hole_2018-10-11 13_05_41,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
21,hole_2018-10-11 13_06_28,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
22,hole_2018-10-11 13_07_10,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
23,hole_2018-10-11 13_07_50,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
24,hole_2018-10-11 13_08_30,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
25,hole_2018-10-11 13_09_04,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
26,hole_2018-10-11 13_10_26,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
27,hole_2018-10-11 13_11_15,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
28,hole_2018-10-11 13_11_59,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
29,hole_2018-10-11 13_12_41,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
30,hole_2018-10-11 13_13_27,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
31,hole_2018-10-11 13_14_03,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
32,hole_2018-10-11 13_15_39,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
33,hole_2018-10-11 13_16_12,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
34,hole_2018-10-11 13_16_52,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
35,hole_2018-10-11 13_17_30,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
36,hole_2018-10-11 13_19_19,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
37,hole_2018-10-11 13_22_24,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
38,hole_2018-10-11 13_23_23,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
39,hole_2018-10-11 13_24_13,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
40,hole_2018-10-11 13_25_22,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
41,hole_2018-10-11 13_25_54,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
42,hole_2018-10-11 13_26_37,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
43,hole_2018-10-11 13_27_47,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
44,hole_2018-10-11 13_29_04,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
45,hole_2018-10-11 13_29_59,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
46,hole_2018-10-11 13_31_19,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
47,hole_2018-10-11 13_34_55,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
48,hole_2018-10-11 13_36_18,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
49,hole_2018-10-11 13_37_21,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
50,hole_2018-10-11 13_38_02,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
51,hole_2018-10-11 13_38_50,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
52,hole_2018-10-11 13_39_55,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
53,hole_2018-10-11 13_41_12,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
54,hole_2018-10-11 13_42_09,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
55,hole_2018-10-11 13_42_53,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
56,hole_2018-10-11 13_44_23,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
57,hole_2018-10-11 13_45_00,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
58,hole_2018-10-11 13_45_38,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
59,hole_2018-10-11 13_46_12,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
60,hole_2018-10-11 13_47_44,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
61,hole_2018-10-11 13_49_24,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
62,hole_2018-10-11 13_49_58,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
63,hole_2018-10-11 13_51_17,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
64,hole_2018-10-11 13_53_44,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
65,hole_2018-10-11 13_54_52,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
66,hole_2018-10-11 13_56_13,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
67,hole_2018-10-11 13_56_54,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
68,hole_2018-10-11 13_57_26,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
69,hole_2018-10-11 13_58_04,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
70,hole_2018-10-11 13_59_17,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
71,hole_2018-10-11 14_00_07,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
72,hole_2018-10-11 14_03_20,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
73,hole_2018-10-11 14_04_10,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
74,hole_2018-10-11 14_05_08,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
75,hole_2018-10-11 14_09_42,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
76,hole_2018-10-11 14_10_30,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
77,hole_2018-10-11 14_12_12,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
78,hole_2018-10-11 14_12_56,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
79,hole_2018-10-11 14_14_44,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
80,hole_2018-10-11 14_15_19,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
81,hole_2018-10-11 14_16_22,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
82,hole_2018-10-11 14_19_30,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
83,hole_2018-10-11 14_20_13,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
84,hole_2018-10-11 14_21_03,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
85,line_2018-10-10 09_39_19,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
86,line_2018-10-11 12_38_10,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
87,line_2018-10-11 12_38_59,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
88,line_2018-10-11 12_39_52,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
89,line_2018-10-11 12_40_36,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
90,line_2018-10-11 12_41_17,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
91,line_2018-10-11 12_42_20,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
92,line_2018-10-11 12_43_04,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
93,line_2018-10-11 12_43_50,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...
94,line_2018-10-11 12_44_47,1280,720,D:\CountAI_Projects\Datasets\archive\captured\...

In [7]:
df = DF[:15]

In [8]:
df

,Image_Name,Image_Width,Image_Height,Image_Location
0,20180531_134722,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
1,20180531_134730,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
2,20180531_135018,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
3,20180531_135032,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
4,20180531_135038,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
5,20180531_135110,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
6,20180531_135111,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
7,20180531_135129,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
8,20180531_135705,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
9,20180531_135709,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
10,20180531_135742,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
11,20180531_135806,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
12,20180531_141608,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
13,20180531_141626,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
14,20180531_141640,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...

In [9]:
def sort_inbuilt(nm):

    nm = str(nm).strip()
    fg = nm.index("_") + 1
    fg = nm[fg:]
    return int(fg)

In [10]:
sr = df["Image_Name"]

In [11]:
sr

0     20180531_134722
1     20180531_134730
2     20180531_135018
3     20180531_135032
4     20180531_135038
5     20180531_135110
6     20180531_135111
7     20180531_135129
8     20180531_135705
9     20180531_135709
10    20180531_135742
11    20180531_135806
12    20180531_141608
13    20180531_141626
14    20180531_141640
Name: Image_Name, dtype: object

In [12]:
fg = sr.apply(sort_inbuilt)

In [13]:
fg

0     134722
1     134730
2     135018
3     135032
4     135038
5     135110
6     135111
7     135129
8     135705
9     135709
10    135742
11    135806
12    141608
13    141626
14    141640
Name: Image_Name, dtype: int64

In [15]:
fg.sort_values(inplace=True)

In [16]:
fg

0     134722
1     134730
2     135018
3     135032
4     135038
5     135110
6     135111
7     135129
8     135705
9     135709
10    135742
11    135806
12    141608
13    141626
14    141640
Name: Image_Name, dtype: int64

In [18]:
df.set_index(fg.index)

,Image_Name,Image_Width,Image_Height,Image_Location
0,20180531_134722,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
1,20180531_134730,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
2,20180531_135018,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
3,20180531_135032,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
4,20180531_135038,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
5,20180531_135110,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
6,20180531_135111,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
7,20180531_135129,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
8,20180531_135705,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
9,20180531_135709,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
10,20180531_135742,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
11,20180531_135806,4608,3456,D:\CountAI_Projects\Datasets\archive\captured\...
12,20180531_141608,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
13,20180531_141626,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...
14,20180531_141640,3456,4608,D:\CountAI_Projects\Datasets\archive\captured\...

In [28]:
img = cv2.imread(df.loc[0]["Image_Location"])

In [29]:
img

array([[[ 29,  40,  68],
        [ 28,  39,  67],
        [ 34,  45,  73],
        ...,
        [  5,  12,  29],
        [  2,   8,  27],
        [  2,   8,  27]],

       [[ 28,  39,  67],
        [ 26,  37,  65],
        [ 30,  41,  69],
        ...,
        [  7,  14,  31],
        [  6,  12,  31],
        [  5,  11,  30]],

       [[ 27,  38,  66],
        [ 25,  36,  64],
        [ 26,  37,  65],
        ...,
        [  6,  13,  30],
        [  5,  12,  29],
        [  7,  14,  31]],

       ...,

       [[ 81,  82,  92],
        [ 93,  94, 104],
        [102, 104, 112],
        ...,
        [  4,   8,  26],
        [  6,  10,  28],
        [  8,  12,  30]],

       [[ 90,  89,  98],
        [ 93,  92, 101],
        [103, 102, 111],
        ...,
        [ 14,  18,  36],
        [  9,  13,  31],
        [  5,   9,  27]],

       [[ 89,  88,  97],
        [ 92,  91, 100],
        [107, 106, 115],
        ...,
        [ 10,  14,  32],
        [  6,  10,  28],
        [  6,  10,  28]]], dtype=uint8)

In [30]:
img.shape

(4608, 3456, 3)

In [46]:
def process_and_store_images(project_name):

    temp_folder = r"D:\CountAI_Projects\Datasets\archive\Exaperimental_Data"

    output_loc = os.path.join(temp_folder,project_name)

    if not os.path.exists(output_loc):
        os.mkdir(output_loc)

    for iter,row in df.iterrows():

        image_loc = row["Image_Location"]
        out_img_loc = os.path.join(output_loc,f"{iter+1}.png")
        shutil.copy2(image_loc,out_img_loc)

In [47]:
process_and_store_images("Expriment1")

In [168]:
img = cv2.imread(r"D:\CountAI_Projects\Datasets\archive\Exaperimental_Data\Expriment1\10.png")

In [169]:
img.shape

(3456, 4608, 3)

In [170]:
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [171]:
 img.shape

(3456, 4608)

In [172]:
cv2.imwrite(r"D:\CountAI_Projects\Datasets\archive\Exaperimental_Data\Expriment1\1_gray.png",img)

True

In [175]:
_,img = cv2.threshold(img,0,255,cv2.THRESH_TOZERO | cv2.THRESH_OTSU)

In [176]:
cv2.imwrite(r"D:\CountAI_Projects\Datasets\archive\Exaperimental_Data\Expriment1\1_thresh.png",img)

True

In [177]:
_

0.0